SHELL = /bin/sh

.PHONY: all
all:
#	cd $(WORK_ROOT)/src/dsc          && $(MAKE)
#	cd $(WORK_ROOT)/src/ztools       && $(MAKE)
	cd $(WORK_ROOT)/src/vbh_comm     && $(MAKE)
	cd $(WORK_ROOT)/src/vbh_server   && $(MAKE)
	cd $(WORK_ROOT)/src/outer_cc   && $(MAKE)
#	cd $(WORK_ROOT)/src/vbh_sdk      && $(MAKE)
#	cd $(WORK_ROOT)/src/vbh_explorer && $(MAKE)
#	cd $(WORK_ROOT)/src/demo               && $(MAKE)
#	cd $(WORK_ROOT)/src/test         && $(MAKE)
	
clean:
#	cd $(WORK_ROOT)/src/dsc          && $(MAKE) clean
#	cd $(WORK_ROOT)/src/ztools       && $(MAKE) clean
	cd $(WORK_ROOT)/src/vbh_comm     && $(MAKE) clean
	cd $(WORK_ROOT)/src/vbh_server   && $(MAKE) clean
	cd $(WORK_ROOT)/src/outer_cc   && $(MAKE) clean
#	cd $(WORK_ROOT)/src/vbh_sdk      && $(MAKE) clean
#	cd $(WORK_ROOT)/src/vbh_explorer && $(MAKE) clean
#	cd $(WORK_ROOT)/src/demo               && $(MAKE)   clean
#	cd $(WORK_ROOT)/src/test         && $(MAKE) clean
	